version: 1.0.{build}

branches:
  only:
    - master
    - testing

image: Visual Studio 2017
clone_folder: c:\projects\blackbone

platform: 
  - Win32
  - x64

configuration: 
  - Debug
  - Debug(DLL)
  - Release
  - Release(DLL)
  
build:
  parallel: true
  project: BlackBone.sln 
  
test_script:
  - ps: vstest.console /logger:Appveyor "build/$env:PLATFORM/$env:CONFIGURATION/BlackboneTest.dll"

skip_commits:
  message: /Driver/